import type { SurfaceConfig } from './types';

export const richTableSurfaces = {
  cellMenu: [
    'rich-table-copy',
    'rich-table-paste',
    '---',
    'rich-table-insert-row-above',
    'rich-table-insert-row-below',
    '---',
    'rich-table-insert-column-left',
    'rich-table-insert-column-right',
    '---',
    'rich-table-merge-cells',
    'rich-table-split-cell',
    '---',
    'rich-table-delete-row',
    'rich-table-delete-column',
  ] as SurfaceConfig,
  headerMenu: [
    'rich-table-copy',
    'rich-table-paste',
    '---',
    'rich-table-insert-row-above',
    'rich-table-insert-row-below',
    '---',
    'rich-table-insert-column-left',
    'rich-table-insert-column-right',
    '---',
    'rich-table-merge-cells',
    'rich-table-split-cell',
    '---',
    'rich-table-sort-asc',
    'rich-table-sort-desc',
    '---',
    'rich-table-delete-row',
    'rich-table-delete-column',
  ] as SurfaceConfig,
};
